CREATE POLICY "usuarios_proprios_analises" ON analises FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "admin_assinaturas" ON assinaturas FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "usuario_gerencia_assinatura" ON assinaturas FOR ALL USING ((auth.uid() = usuario_id)) WITH CHECK ((auth.uid() = usuario_id));
CREATE POLICY "atualizacao_dono_ou_admin" ON base_juridica FOR UPDATE USING (((usuario_id = auth.uid()) OR (usuario_id IS NULL)));
CREATE POLICY "insercao_usuario_autenticado" ON base_juridica FOR INSERT USING (true) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "leitura_global_ou_propria" ON base_juridica FOR SELECT USING (((usuario_id IS NULL) OR (usuario_id = auth.uid())));
CREATE POLICY "insercao_autenticados" ON base_juridica_relacoes FOR INSERT USING (true) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "leitura_autenticados" ON base_juridica_relacoes FOR SELECT USING ((auth.uid() IS NOT NULL));
CREATE POLICY "insercao_autenticados" ON base_teses FOR INSERT USING (true) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "leitura_autenticados" ON base_teses FOR SELECT USING ((auth.uid() IS NOT NULL));
CREATE POLICY "checklist_proprio" ON checklist FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "admin_clientes" ON clientes FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "clientes_proprios" ON clientes FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "usuarios_proprios" ON divida_ativa FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "entradas_proprias" ON entradas FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "admin_acesso_total_permissoes" ON extensao_permissoes FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text)) WITH CHECK (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "usuario_le_suas_permissoes" ON extensao_permissoes FOR SELECT USING ((auth.uid() = usuario_id));
CREATE POLICY "admin_tudo_kanban_colunas" ON kanban_colunas FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "usuario_gerencia_propria_kanban_colunas" ON kanban_colunas FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "usuarios_proprios" ON mensagens_rapidas FOR ALL USING ((auth.uid() = user_id));
CREATE POLICY "admin_tudo_modulos_permissoes" ON modulos_permissoes FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "usuario_le_propria_modulos_permissoes" ON modulos_permissoes FOR SELECT USING ((auth.uid() = usuario_id));
CREATE POLICY "insercao_autenticados" ON motor_regras FOR INSERT USING (true) WITH CHECK ((auth.uid() IS NOT NULL));
CREATE POLICY "leitura_autenticados" ON motor_regras FOR SELECT USING ((auth.uid() IS NOT NULL));
CREATE POLICY "usuarios_proprios" ON prospeccao_clientes FOR ALL USING ((auth.uid() = user_id));
CREATE POLICY "admin_recuperacoes" ON recuperacoes FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "usuario_ve_seus_relatorios" ON relatorios_importacao FOR ALL USING ((auth.uid() = usuario_id));
CREATE POLICY "acesso publico sessoes" ON sessoes_ativas FOR ALL USING (true);
CREATE POLICY "admin_sessoes" ON sessoes_ativas FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "acesso publico tb_cest" ON tb_cest FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_cfop" ON tb_cfop FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_cnae" ON tb_cnae FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_csosn" ON tb_csosn FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_cst" ON tb_cst FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_ncm" ON tb_ncm FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_oportunidades" ON tb_oportunidades FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_reforma" ON tb_reforma_tributaria FOR SELECT USING (true);
CREATE POLICY "acesso publico tb_teses" ON tb_teses FOR SELECT USING (true);
CREATE POLICY "admin_usuarios" ON usuarios FOR ALL USING (((auth.jwt() ->> 'email'::text) = 'marcosvini864@gmail.com'::text));
CREATE POLICY "usuarios_proprios" ON usuarios FOR ALL USING ((auth.uid() = id));